### Data preprocessing code
The downloaded data on the different variants will need to be pre-merged due to the same dates and different locations, and the merged data will be the **differential** data, which will then be summed up to get the summation data.
```
Note that the data downloaded here are daily sampling data from various locations and are not representative of the whole country and need to be multiplied by a factor based on the national incidence
```

In [1]:
import pandas as pd
import numpy as np
import time
from datetime import date
import csv

In [2]:
#Here you change the name of the file to be read in, and the name of the column to be read in.
prealphadata = pd.read_csv("../data/omicron.CSV",usecols=["Date","Region","Number of Omicron cases"])
prealphadata

            Date           Region  Number of Omicron cases
0     01/11/2021    West Midlands                        1
1     01/11/2021           London                        1
2     02/11/2021           London                        2
3     02/11/2021       South East                        1
4     03/11/2021           London                        1
...          ...              ...                      ...
1162  20/03/2022  East of England                      141
1163  20/03/2022           London                       24
1164  20/03/2022       South West                       14
1165  20/03/2022       South East                      135
1166  20/03/2022          Unknown                        2

[1167 rows x 3 columns]

In [3]:
alphanp = np.zeros(600,dtype=int)       #As the number of days gets larger, the 100 here may have to be correspondingly larger.
for idx, row in prealphadata.iterrows():
    d,m,y = [int(i) for i in row[0].split('/')]
    alphanp[(date(y,m,d)-date(2020,10,1)).days]+=row[2]     #Merge data with the same date

In [4]:
sumalpha = np.zeros(600,dtype=int)
s = 0
for i in range(len(alphanp)):
    s+=alphanp[i]
    sumalpha[i]=s                               #totalization
sumalpha

array([      0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       2,       5,       6,
             6,       7,       8,       8,       8,       8,       9,
             9,      11,      11,      11,      16,      18,      20,
            20,      20,      22,      23,      30,      30,      37,
            59,      86,     120,     145,     197,     275,     381,
           546,     760,    1042,    1412,    2246,    3502,    5028,
          7141,   10092,   13165,   17451,   27087,   39079,   56826,
         71781,   85790,  103213,  120977,  142871,  159210,  177521,
        199077,  217261,  230445,  249666,  273249,  297003,  329078,
        354664,  374779,  387991,  410854,  438203,  469252,  494931,
        520851,  544011,  561131,  577937,  606424,  632661,  653869,
        674204,  696155,  716871,  736266,  764821,  790687,  815260,
        837037,  861218,  881687,  899653,  930312,  956197,  982765,
       1007814, 1029181, 1045702, 1062819, 1091153, 1112769, 1134263,
       1155722, 1173593, 1187740, 1199085, 1218193, 1235482, 1252264,
       1265768, 1276970, 1284738, 1290822, 1305281, 1316229, 1327790,
       1337591, 1342481, 1349179, 1354190, 1363926, 1371774, 1378420,
       1384904, 1390263, 1393551, 1397577, 1407360, 1415854, 1423894,
       1430650, 1436649, 1441766, 1447217, 1459823, 1471969, 1485028,
       1498762, 1512100, 1522761, 1532531, 1557682, 1578539, 1593217,
       1609931, 1622525, 1629377, 1629935, 1629935, 1629935, 1629935,
       1629935, 1629935, 1629935, 1629935, 1629935, 1629935, 1629935,
       1629935, 1629935, 1629935, 1629935, 1629935, 1629935, 1629935,
       1629935, 1629935, 1629935, 1629935, 1629935, 1629935, 1629935,
       1629935, 1629935, 1629935, 1629935, 1629935, 1629935, 1629935,
       1629935, 1629935, 1629935, 1629935, 1629935, 1629935, 1629935,
       1629935, 1629935, 1629935, 1629935, 1629935, 1629935, 1629935,
       1629935, 1629935, 1629935, 1629935, 1629935, 1629935, 1629935,
       1629935, 1629935, 1629935, 1629935, 1629935, 1629935, 1629935,
       1629935, 1629935, 1629935, 1629935, 1629935])

In [5]:
#Write file, file name needs to be changed
alphdf = pd.DataFrame(alphanp)
alphdf.to_csv("../processed/diff_omicron.csv",index=None)
sumdf = pd.DataFrame(sumalpha)
sumdf.to_csv("../processed/sum_omicron.csv",index=None)